2020-09-04 18:06:00,786 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 26, in index
    msg.body = render_template('new_user_email.txt', order=order)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andrii/PycharmProjects/work_on_ship/app/templates/new_user_email.txt", line 3, in top-level template code
    is now a follower. Click on the following link to visit {{follower.nickname}}'s profile page:
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'follower' is undefined
2020-09-04 18:06:37,489 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
2020-09-04 18:06:51,022 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 26, in index
    msg.body = render_template('new_user_email.txt', order=order)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andrii/PycharmProjects/work_on_ship/app/templates/new_user_email.txt", line 5, in top-level template code
    {{url_for('order')}}
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'order'. Did you mean 'index' instead?
2020-09-04 18:07:26,216 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 26, in index
    msg.body = render_template('new_user_email.txt', order=order)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andrii/PycharmProjects/work_on_ship/app/templates/new_user_email.txt", line 5, in top-level template code
    {{order}}
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'order'. Did you mean 'index' instead?
2020-09-04 18:07:36,432 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
