2020-09-05 15:00:58,849 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 26, in index
    msg.body = render_template('new_user_email.txt', order=order)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andrii/PycharmProjects/work_on_ship/app/templates/new_user_email.txt", line 4, in top-level template code
    {{order}}
  File "/home/andrii/PycharmProjects/work_on_ship/app/models.py", line 15, in __repr__
    return 'User (First_name=%first_name, Last_name=%last_name, Email=%email, Number=%number)' % (
TypeError: must be real number, not str
2020-09-05 15:01:31,001 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
2020-09-05 15:01:42,675 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 26, in index
    msg.body = render_template('new_user_email.txt', order=order)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andrii/PycharmProjects/work_on_ship/app/templates/new_user_email.txt", line 4, in top-level template code
    {{order}}
  File "/home/andrii/PycharmProjects/work_on_ship/app/models.py", line 15, in __repr__
    return 'User (First_name=%first_name, Last_name=%last_name, Email=%email)' % (
TypeError: must be real number, not str
2020-09-05 15:09:09,506 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
