2020-09-04 19:17:42,699 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 25, in index
    print(type[Config.ADMINS])
TypeError: 'type' object is not subscriptable
2020-09-04 19:18:46,510 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
2020-09-04 19:18:56,723 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 29, in index
    mail.send(msg)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 190, in send
    message.as_bytes() if PY3 else message.as_string(),
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 385, in as_bytes
    return self._message().as_bytes()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 314, in _message
    msg = self._mimetext(self.body)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 303, in _mimetext
    return MIMEText(text, _subtype=subtype, _charset=charset)
  File "/usr/lib/python3.8/email/mime/text.py", line 42, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python3.8/email/message.py", line 321, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python3.8/email/message.py", line 356, in set_charset
    cte(self)
  File "/usr/lib/python3.8/email/encoders.py", line 60, in encode_7or8bit
    orig.decode('ascii')
AttributeError: 'User' object has no attribute 'decode'
2020-09-04 20:10:48,948 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
2020-09-04 20:11:01,038 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 27, in index
    mail.send(msg)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 181, in send
    if message.has_bad_headers():
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 400, in has_bad_headers
    headers = [self.sender, self.reply_to] + self.recipients
TypeError: can only concatenate list (not "str") to list
2020-09-04 20:13:03,146 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
2020-09-04 20:13:14,371 ERROR: Exception on /index [POST] [in /home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrii/PycharmProjects/work_on_ship/app/routes.py", line 27, in index
    mail.send(msg)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 190, in send
    message.as_bytes() if PY3 else message.as_string(),
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 385, in as_bytes
    return self._message().as_bytes()
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 314, in _message
    msg = self._mimetext(self.body)
  File "/home/andrii/PycharmProjects/work_on_ship/venv/lib/python3.8/site-packages/flask_mail.py", line 303, in _mimetext
    return MIMEText(text, _subtype=subtype, _charset=charset)
  File "/usr/lib/python3.8/email/mime/text.py", line 42, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python3.8/email/message.py", line 321, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python3.8/email/message.py", line 356, in set_charset
    cte(self)
  File "/usr/lib/python3.8/email/encoders.py", line 60, in encode_7or8bit
    orig.decode('ascii')
AttributeError: 'User' object has no attribute 'decode'
2020-09-04 20:13:39,262 INFO: Work_on_ship startup [in /home/andrii/PycharmProjects/work_on_ship/app/__init__.py:46]
